baseURL: "https://piyopanman.dev/"
title: Piyopanman
paginate: 10
theme: PaperMod
defaultContentLanguage: "ja"
languageCode: "ja"
hasCJKLanguage: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON  

social:
  twitter: "hiyoko_coder"    

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Piyopanman
  description: "Piyopanman's Site"
  keywords: [Blog, Portfolio, DailyReport]
  # author: Me
  images: ["/images/piyopanman.png"]
  DateFormat: "2006年01月02日"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/piyopanman.png"
    favicon16x16: "images/piyopanman.png"
    favicon32x32: "images/piyopanman.png"
    apple_touch_icon: "images/piyopanman.png"
    safari_pinned_tab: "images/piyopanman.png"

  label:
    text: "Home"
    icon: "images/piyopanman.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Piyopanman
    subtitle: "🐤つかまり立ちです🐤"
    imageUrl: "images/piyopanman.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "very kawaii hiyoko"
    buttons:
      - name: 日報
        url: daily-reports
      - name: メモ
        url: memos      
      - name: 記事
        url: articles


  # home-info mode
  homeInfoParams:
    Title: "Piyopanman.dev 🐤"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/hiyoko_coder/"
    - name: github
      url: "https://github.com/Piyopanman/"
    - name: qiita
      url: "https://qiita.com/Piyopanman/"  

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    # URL: "https://github.com/Piyopanman/piyopanman.dev/content"
    URL: ""
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: daily-reports
      name: 日報
      url: /daily-reports/
      weight: 1
    - identifier: memos
      name: メモ
      url: /memos/
      weight: 2
    - identifier: articles
      name: 記事
      url: /articles/
      weight: 3           
    - identifier: tags
      name: タグ
      url: /tags/
      weight: 5
    # - identifier: categories
    #   name: カテゴリ
    #   url: /categories/
    #   weight: 5
    - idendifier: search
      name: 検索
      url: /search/
      weight: 10
    
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai